### PR TITLE
Do as-is conversion ruby to python3

### PR DESCRIPTION
**Pull request by CAMOBAP**

### CODE REVIEW

**Comment by ronaldtse** [comment]
@CAMOBAP can we merge this now?

**Comment by CAMOBAP** [comment]
@ronaldtse a couple of important files still missing, like localized_string.rb. I'm working on it right now

**Comment by CAMOBAP** [comment]
Conversion is still in progress and will be continued in other PRs

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP ! Let's make this available on PyPI ASAP.

**Comment by CAMOBAP** [comment]
@ronaldtse i still working on it, is it make sens to do some "alpha" release?

**Comment by ronaldtse** [comment]
Yes please!

**Pull request merged**
